# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'tarot_flash_cards' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for tarot_flash_cards
  react_native_path = "../node_modules/react-native"
  pod "Yoga", :path => "#{react_native_path}/ReactCommon/yoga"
  pod 'React', :path => react_native_path
  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

  target 'tarot_flash_cardsTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'tarot_flash_cards-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for tarot_flash_cards-tvOS

  target 'tarot_flash_cards-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
